name:   CD Pipeline

on:
  push:
    branches: [ "master" ]

jobs:

  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3

    - name: Set up Go
      uses: actions/setup-go@v4
      with:
        go-version: '1.14'

    - name: Install Dependencies
      run: go mod download   

    - name: Run Build
      run: go build -o ./cmd/server

    - name: Build Docker Image
      run: |
        docker build -t ${{ secrets.DOCKER_USERNAME }}/taskkkkk:latest .

    - name: Push Docker Image
      run: |
        docker login -u ${{ secrets.DOCKER_USERNAME }} -p ${{ secrets.DOCKER_PASSWORD }}
        docker image push ${{ secrets.DOCKER_USERNAME }}/taskkkkk:latest
